### PR TITLE
documentation updatation

### PR DESCRIPTION
**Pull request by kalevivek11**
Added one note

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

**Review by Mariangela — APPROVED** [review]

**Comment by Mariangela** [comment]
@fazlan-nazeem , is this fix applicable to 3.1.0 and 3.2.0?

**Comment by fazlan-nazeem** [comment]
PR has been accidentally merged before review. Therefore reverting.

**Comment by RAVEENSR** [comment]
@kalevivek11 

The note you have put in here is wrong. In here the `adminUsername` and the `adminPassword` credentials are used to access admin services. Admin services use the super tenant admin's credentials. So someone can change the super tenant admin username or the super tenant admin password according to their will. In that case password value is not **admin**. So we cannot add the following note as it the password can be other than the value `admin.` 

> !!! note 
>     The password should be admin for `adminUsername` otherwise you will get an invalid username error in the Publisher logs.
> 

@Mariangela 

We can improve the description fields by stating that the `adminUsername` and the `adminPassword` are the credentials defined under super tenant in the API Manager's `deployment.toml` file. This change is applicable to APIM 3.1.0 and 3.2.0 versions as well.

**Comment by kalevivek11** [comment]
Try giving any other user name other than admin, if super admin username is
different, u will understand the issue,

**Comment by RAVEENSR** [comment]
@kalevivek11 
That is because you have not correctly renamed the admin password or did not create the new admin user in the correct manner.

If you have started the wso2server.sh once and then replace the admin username and password with your new username and password it will not work properly. Since you have already started the server, the default `admin` user will be created as the super tenant username. What you can do is changing the password of that already created `admin` user. To do that refer [1, 2]. Then you need to change the analytics worker **deployment.yaml** file(need to provide the base64 encoded new password for `auth.configs` password field) and the analytics dashboard **deployment.yaml** file(need to provide new admin password for `adminPassword`, `kmPassword` entries in the `auth.configs` and under  `# credentials for worker nodes` section)

If you change the admin username and admin password for super tenant in the deployment.yaml of the API Manager before starting the server for the first time, it will create the admin user that you have provided. Then as mentioned above, you need to provide the new admin username and new admin passwords for  analytics worker **deployment.yaml** file and the analytics dashboard **deployment.yaml** file.

Let's say you have now already started the server and you want to change the admin username and admin password. Then you need to log into the management console as the super tenant admin user(still the APIM **deployment.toml** file has `admin/admin` as the super tenant credentials) and create new user with the admin role and assign other necessary admin roles for already created service provider(SP) apps. Then you can stop the APIM server and change the super tenant credentials in the **deployment.toml** file of the API Manager. After that, as mentioned above, you need to provide the new admin username and new admin passwords for  analytics worker **deployment.yaml** file and the analytics dashboard **deployment.yaml** file.

I have tested these scenarios and they are working as expected.

[1] https://apim.docs.wso2.com/en/3.0.0/administer/product-security/logins-and-passwords/maintaining-logins-and-passwords/#maintaining-logins-and-passwords
[2] https://docs.wso2.com/display/ADMIN44x/Changing+a+Password

**Comment by RAVEENSR** [comment]
@kalevivek11 
We have many customers using this feature without any issue. I am pretty sure that you are doing something wrong here. Probably due to a configuration issue. BTW, why don't you take our subscriptions? If you do have a valid subscription, you can ask this via our support portal. They will help you with the configurations.

**Comment by RAVEENSR** [comment]
@kalevivek11
We have many customers using this feature without any issue. We assume that you are doing something wrong here. Probably due to a configuration issue. Could you please let us know whether you have taken our subscription? If you do have a valid subscription, you can ask this via our support portal. They will help you with the configurations. If you don't have a subscription and if you could create a wso2 subscription, we would be more than happy to revisit and assist you with your deployment.

**Pull request merged**
