### PR TITLE
[3.1.0] Update 2.x to 3.1 artifacts migration scripts

### PR DESCRIPTION
**Pull request by chashikajw**
## Purpose
As $subject this pr will update the follwing migration scripts to address the mentined 2 issues.

- apim210_to_apim310_gateway_artifact_migrator.sh

- apim200_to_apim310_gateway_artifact_migrator_for_tenants.ps1

## Goals

Fixes https://github.com/wso2/product-apim/issues/9378
Fixes https://github.com/wso2/product-apim/issues/9391

### CODE REVIEW

**Review by Mariangela — APPROVED** [review]

**Comment by Mariangela** [comment]
@chashikajw , should a similar fix be done for the 3.2.0 docs?

**Comment by Mariangela** [comment]
@tharindu1st , please confirm this fix.

**Comment by chashikajw** [comment]
> @chashikajw , should a similar fix be done for the 3.2.0 docs?

support teams ask only for this. but seems like we need a fix for 3.2 as well. I will send a pr for that as well.

**Comment by Mariangela** [comment]
@chashikajw , did u send a similar fix for 3.2.0 and master for this already?

**Comment by chashikajw** [comment]
> @chashikajw , did u send a similar fix for 3.2.0 and master for this already?

Not yet and the fix was a bit changed and will send a pr to 3.2 today.

**Comment by chashikajw** [comment]
> > @chashikajw , did u send a similar fix for 3.2.0 and master for this already?
> 
> Not yet and the fix was a bit changed and will send a pr to 3.2 today.

Sent the pr. https://github.com/wso2/docs-apim/pull/2414

**Pull request merged**
