### PR TITLE
Fix postgres database type in migration guide

### PR DESCRIPTION
**Pull request by hiddewie**
I have no idea where the second change in en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-300.md came from

### CODE REVIEW

**Comment by Mariangela** [comment]
@bhathiya , please share your feedback.

**Comment by bhathiya** [comment]
As per the code, it must be "postgre" at the moment. Ideally, it should be either "postgres" or "postgresql". We have to fix it in the product first. Until that we shouldn't merge this PR. 

@tharindu1st plz note.

**Comment by Mariangela** [comment]
I created a git issue [1] to track the change that is needed in API-M.

[1] https://github.com/wso2/product-apim/issues/7741

**Comment by hiddewie** [comment]
@Mariangela Thank you for the comment. I never noticed that the actual configuration requires `postgre`. Thank you for changing the code as well!

**Pull request merged**
