### PR TITLE
Point to choreo insights doc space

### PR DESCRIPTION
**Pull request by ruwiniwj**
## Purpose
Point to choreo insights doc space

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

**Comment by fazlan-nazeem** [comment]
This page also needs to be pointed to the choreo docs

**Comment by samgnaniah** [comment]
If we are deleting these pages, we need to configure redirects in the mkdocs.yaml file as well.

**Comment by ruwiniwj** [comment]
> This page also needs to be pointed to the choreo docs
> https://apim.docs.wso2.com/en/latest/api-analytics/configure-alerts/

Fixed with 9dfe66d36f08b6a81d4e4ad274aee3ceb813342c

**Comment by ruwiniwj** [comment]
> If we are deleting these pages, we need to configure redirects in the mkdocs.yaml file as well.

Fixed with https://wso2.com/choreo/docs/insights/derive-insights/#reports

**Review by fazlan-nazeem — APPROVED** [review]

**Review by samgnaniah — APPROVED** [review]

**Pull request merged**
