### PR TITLE
Broken links master

### PR DESCRIPTION
**Pull request by nilminiwso2**
broken links - warning log

### CODE REVIEW

**Comment by samgnaniah** [comment]
What are the images we have deleted?

**Comment by nilminiwso2** [comment]
> What are these images that have been deleted?

These are not images. They are .md files inside some of the 'assets' directories. They contained one sentence like 'images for the registry should be added here.' Sort of like a intro page or readme  for the folders. I don't think they serve any purpose. Therefore, removed them. We don't need a intro/readme for 'assets/img/integrate/connectors' for example, do we?

**Comment by samgnaniah** [comment]
Ah I see. Makes sense to delete those. There are 3 .md files with more content in there, for example, rule mediator. Are these ones not relevant anymore?

**Comment by nilminiwso2** [comment]
> Ah I see. Makes sense to delete those. There are 3 .md files with more content in there, for example, rule mediator. Are these ones not relevant anymore?

- Yeah. The rule mediator was removed from the MI sometime back.  @Nirothipan Do we have any plans of bringing this back for APIM4?
- And the 'jms-transport-properties.md' seems to be a duplicate of 'jms-transport-parameters.md'.
- Removed 'managing_log_growth.md' from 'mi-observe' folder because it needs to be moved to the 'setup' section. This change is already in place for EI 7.1.0. Therefore, when we migrate the Setup content, this topic will get moved.

**Review by samgnaniah — APPROVED** [review]

**Comment by Nirothipan** [comment]
> > Ah I see. Makes sense to delete those. There are 3 .md files with more content in there, for example, rule mediator. Are these ones not relevant anymore?
> 
> * Yeah. The rule mediator was removed from the MI sometime back.  @Nirothipan Do we have any plans of bringing this back for APIM4?
No we aren't.

**Pull request merged**
