### PR TITLE
fixed note on tenant config

### PR DESCRIPTION
**Pull request by Mariangela**
## Purpose
- fixes A-2118 
- fixed note on tenant config
- https://github.com/wso2/docs-apim/issues/5312

### CODE REVIEW

**Comment by tharindu1st** [comment]
@AnuGayan @ruks  is this needed from 4.0 onwards ?

**Comment by AnuGayan** [comment]
Yes, We don't need in ELK based analytics

**Comment by Mariangela** [comment]
@ruks and @AnuGayan, so is it correct to understand that we can remove this note from 4.0.0 and newer versions?

**Comment by ruks** [comment]
> @ruks and @AnuGayan, so is it correct to understand that we can remove this note from 4.0.0 and newer versions?

yes, this is used in SP-based analytics to view analytics dashboards, APIM 400 onwards we don't have SP dashoards.

**Review by AnuGayan — APPROVED** [review]

**Pull request merged**
