### PR TITLE
Modify the docs on scope schemes

### PR DESCRIPTION
**Pull request by Chamindu36**
**[Please don’t merge Until  WUM fix is released]**

## Purpose
Change the description of adding oauth2 scopes using an open API swagger definition.

## Goals
Fixes: https://github.com/wso2/product-apim-tooling/issues/271

## Approach
Previously it stated that name of the security scheme when adding scopes should be "default". But with the newest fix, this name can be an arbitrary one. This will state that change in docs.
When adding user roles for scopes there is the standard keyword to use. That also stated in here.

image

## User stories
Users can follow the steps to create API using Swagger definition without changing the name of the security scheme.

### CODE REVIEW

**Comment by Mariangela** [comment]
@Chamindu36 , pls let me know when the WUM fix is released and also details of the WUM fix such as date it was released as that information needs to be added to the document.

**Comment by Chamindu36** [comment]
Sure. I’ll do that.

**Comment by bhathiya** [comment]
@Chamindu36 do we still need to keep this open?

**Comment by Chamindu36** [comment]
> @Chamindu36 do we still need to keep this open?

Yeah ayya. This is pending until the related WUM is released.

**Comment by bhathiya** [comment]
Shall we close this for now and reopen whenever we can merge?

**Comment by Chamindu36** [comment]
> Shall we close this for now and reopen whenever we can merge?

Ok sure. will do.

**Pull request merged**
