### PR TITLE
Document use of default attribute in application attributes

### PR DESCRIPTION
**Pull request by msm1992**
## Purpose
This PR documents the use of default attribute in application attributes

### CODE REVIEW

**Comment by Mariangela** [comment]
@msm1992 , is this only applicable to 3.1.0 or is it applicable to 3.0.0 as well?

**Comment by msm1992** [comment]
@Mariangela it is applicable for 3.0.0 as well.

**Comment by Mariangela** [comment]
@msm1992 , pls send these changes to the 3.0.0 branch as well, so that it will get reflected in the 3.0.0 docs as well.

**Comment by msm1992** [comment]
Please find the 3.0.0 doc change at https://github.com/wso2/docs-apim/pull/898

**Pull request merged**
