### PR TITLE
[3.1.0][DON'T MERGE]Add proxy support related docs for APICTL

### PR DESCRIPTION
**Pull request by npamudika**
## Purpose
Add fixes related to https://github.com/wso2/product-apim-tooling/issues/503

### CODE REVIEW

**Review by Mariangela — APPROVED** [review]

**Comment by uvindra** [comment]
This PR is awaiting the patch release of apictl v3.1.5

**Comment by bhathiya** [comment]
what's the plan for this?

**Comment by npamudika** [comment]
> what's the plan for this?

We are planning to do the patch release after the 4.0 major release

**Comment by bhathiya** [comment]
> > what's the plan for this?
> 
> We are planning to do the patch release after the 4.0 major release

Shall we close  the PR  for now and send again when we need it?

**Comment by npamudika** [comment]
Closing until we proceed with the 3.1.5 patch release

**Pull request closed without merging**
