### PR TITLE
Move supported cipher suites document under APIM doc space

### PR DESCRIPTION
**Pull request by vithu30**
Related issue - https://github.com/wso2/docs-apim/issues/2025

### CODE REVIEW

**Comment by vithu30** [comment]
@sureshthivanka, @mathuriga Could you please review the changes.

**Review by sureshthivanka — CHANGES_REQUESTED** [review]
@vithu30 shall we double check the below areas,

- TLS versions 
- Weak ciphers

**Comment by Mariangela** [comment]
@vithu30 , can you please check Suresh Rupasinghe's ( sureshthivanka) comment.

**Comment by vithu30** [comment]
@sureshthivanka, as per the discussion we had, I have removed TLSv1.3 cipher suites from the supported protocols list. I believe we can have lower TLS version cipher suites under weak ciphers section. WDYT?

**Review by sureshthivanka — APPROVED** [review]
+1 to proceed.

**Review by Mariangela — APPROVED** [review]

**Comment by Mariangela** [comment]
@vithu30 , do we need to add this fix to 3.1.0 and 3.0.0? If yes, please send PRs for it.

**Pull request merged**
