### PR TITLE
New Architecture Diagram

### PR DESCRIPTION
**Pull request by samgnaniah**
Fixes https://github.com/wso2/docs-apim/issues/4509

### CODE REVIEW

**Comment by Mariangela** [comment]
@samgnaniah , when adding the other diagram, lets remove the -2 in the name of the image.

**Comment by samgnaniah** [comment]
> @samgnaniah , when adding the other diagram, lets remove the -2 in the name of the image.

Done.

**Comment by Mariangela** [comment]
This is the image that Dinushantha redid for us by simply fixing the typo.

Diagram_correction

**Comment by samgnaniah** [comment]
Closing this and sending a new PR.

**Pull request closed without merging**
